type hints: typing.Optional[...] -> typing.Optional[typing.Union[...]]
Fixes the following error on Python 3.14:

TypeError: typing.Optional requires a single type. Got (<class
'PySide6.QtGui.QKeySequence'>, <class 'PySide6.QtCore.QKeyCombination'>,
<enum 'StandardKey'.

Change-Id: Id1fe45d31cc38a337caa55a86f509c3f88c0b683
Reviewed-by: Christian Tismer <tismer@stackless.com>
Reviewed-by: Łukasz Patron <priv.luk@gmail.com>