standarddialogs example: Fix error when checking dialog options
The helper widget displaying the dialog options used int(0)
as default value when building the options flags, causing:

standarddialogs.py", line 274, in set_color
    options_value = self._color_options.value()
  File "examples/widgets/dialogs/standarddialogs/standarddialogs.py", line 33, in value
    result |= value
TypeError: unsupported operand type(s) for |=: 'int' and 'ColorDialogOption'
 options_value = self._color_options.value()

Fix this by passing a zero value of the correct options type.

Pick-to: 6.8
Task-number: PYSIDE-1735
Change-Id: Ia82edb2403a9b4580fe3202d75e77da86290fdfe
Reviewed-by: Cristian Maureira-Fredes <cristian.maureira-fredes@qt.io>